---
- name: Reset kubeadm
  command: kubeadm reset -f
  become: true
- name: Run kubeadm init
  command: kubeadm init --apiserver-cert-extra-sans=192.168.1.101 --pod-network-cidr=192.168.0.0/16
  become: true
- name: Setup kubeconfig
  become: false
  file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true
- name: Copy kubeconfig
  shell: sudo cp /etc/kubernetes/admin.conf "{{ ansible_user_dir }}/.kube/config"
- name: Set kubeconfig permisions
  file:
    path: "{{ ansible_user_dir }}/.kube/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  become: true
- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
- name: Copy join command to local file
  copy: 
    dest: "/tmp/join_command.sh" 
    content: "{{ join_command.stdout_lines[0] }}"
  become: false
  delegate_to: localhost
