---
- name: Run kubeadm init
  command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10"  --node-name k8s-master --pod-network-cidr=192.168.0.0/16

- name: Setup kubeconfig
  command: "{{ item }}"
  with_items:
   - mkdir -p /home/vagrant/.kube
   - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
   - chown vagrant:vagrant /home/vagrant/.kube/config
- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
- name: Copy join command to local file
  copy: 
    dest: "/tmp/join_command.sh" 
    content: "{{ join_command.stdout_lines[0] }}"
  become: false
  delegate_to: localhost
